redis-ha:
  enabled: false

controller:
  replicas: 1

server:
  replicas: 1

repoServer:
  replicas: 1

applicationSet:
  replicas: 1

certificate:
  enabled: true

global:
  domain: argocd.test.com

server:
  ingress:
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    enabled: true
    ingressClassName: nginx
    tls: true
